### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by JJ-G4M3R** [veldlabs/miki-bot#233]
Does anyone know why the prune commands don't work??

**Comment by JJ-G4M3R** [comment]
I cannot use `>prune` but `>prune <amount>` and `>prune <amount> <@user>` work. Why is this?

**Comment by adv0catus** [comment]
You need to set an amount.

**Comment by JJ-G4M3R** [comment]
This is from the doccumentation:


>prune | Removes all messages in the last 100 messages. | >prune
-- | -- | --

**Comment by Pao-Lumu** [comment]
The Github documentation is outdated. `>help prune` shows the latest documentation.

Currently:
`PRUNE`
`Description`
`Clean up your messages in just a second!`
`Usage`
`>prune [amount]`

**Comment by adv0catus** [comment]
Updated the documentation.

**Comment by adv0catus** [comment]
Just confirmed it does work, `>prune` does delete 100 messages, but there is a momentarily delay.

Restoring documentation.

**Comment by Pao-Lumu** [comment]
Looked into this:

`>prune` without params needs to have at least 100 messages in a channel to work.
Similarly, `prune #` requires you have at least `#` messages in your channel.
`>prune # @user` works, regardless of how many messages are in the channel, even if 0.

This bug is valid.

Proof:
http://imgur.com/a/kT8i8

Edit: Probably a bug [here](https://github.com/velddev/Meru/blob/master/Meru/SDK/RuntimeChannel.cs#L58) in Meru. (At any rate, that method should have its variables renamed.)
Otherwise: [Here](https://github.com/velddev/Miki/blob/master/Miki/Modules/AdminModule.cs#L242) in AdminModule.

**Comment by Drummss** [comment]
I realise this is closed now but the bug in question has been patched in a recent pull request I did. #258 
Check it out for the full list of changes to the prune command! 😄
