### ISSUE TITLE
NSFW tags dont work

### ISSUE THREAD

**Issue by 888lollol** [veldlabs/miki-bot#337]
Tags for yandere and e621 dont work. Additionally, all e621 searches end up with the same image.

**Comment by velddev** [comment]
I'll look into it shortly

**Comment by Pao-Lumu** [comment]
e621 showing same image was fixed in PR #375.
Fix will go live when Veld decides to push it to live.

The tag search still doesn't work. I'm looking into it.


Worth noting: Searching for "banned tags" will return a result, but not one with the tags that are banned. So that code is, at the very least, being executed correctly.

**Comment by Pao-Lumu** [comment]
`{'success': False, 'reason': 'You can only search up to 6 tags at once'}`
5 banned tags, plus 1 rating = 6 tags.
6 terms works.
7 does not.
This goes for e621, yande.re, and konachan alike.


Also: yande.re OH SO HELPFULLY returns an image of a cute anime girl, instead of a JSON error like Konachan and e621.
[In their API.](https://yande.re/post.json?limit=1&tags=holy%20shit%20thats%20what%20I%20call%20inept)
Their.
Programming.
API.


The only way I can see to fix this is to remove banned terms, and then filter out posts with banned tags after the fact, rather than passing the banned terms to the servers.
There's a bit of overhead for that, but at least it'll function.

**Comment by velddev** [comment]
Resolved this.
