### ISSUE TITLE
Moderate pastas per guild

### ISSUE THREAD

**Issue by kstrumpets** [veldlabs/miki-bot#341]
There's a specific pasta that makes everyone in the server uncomfortable, but it can't be deleted. I would really like it if mods and admins of a server can delete pastas so that gross ones like the one I mentioned can stop making people uncomfortable. If necessary, making it so Miki pastas are confined to one server, much like how the levels for Miki are different for each person in a server.

The command I'm referring to is >pasta lance
What it says is something extremely gross and dehumanizing.

**Comment by adv0catus** [comment]
Pastas will never be able to be deleted by a server owner or administrator or moderator. The reason for that is because pastas are not just for one server, they're used globally. Anyone can become a server owner or administrator or moderator because anyone can make a server and add Miki. This would give them the power to delete any pasta they want for everyone that uses Miki. This creates obvious and wide spread problems.

With that being said, let the staff on the Miki support server know about any offensive pastas and we will review it and act accordingly. Currently, the solution to offensive pastas is for us to manually review them.

This pasta is being reviewed now, but in the future, creating a GitHub issue ticket isn't the way to go about this. This isn't inherently an issue with Miki's code and is not a bug.

**Comment by Drummss** [comment]
I think a system to blacklist a pasta on your server would be pretty cool.
