### ISSUE TITLE
Set levels manually, maybe >setlevel @[user] [lvl#]? 

### ISSUE THREAD

**Issue by bucca2** [veldlabs/miki-bot#354]
I didn't install Mikibot right at the beginning of the server and a lot of users are already on level 9 or so, it wouldn't be fair to make them start over. If admins could manually add levels that would be great.

**Comment by adv0catus** [comment]
Levels are based on the amount of experience gained. While local levels are local, they're part of the global experience, which is a combination of experience across all servers the user is a part of that has Miki. Being able to modify that, along with such things as mekos and pastas isn't something that can really be done, since it's not a chance that is specific and isolated to your server.

If just the local experience was modifiable, it creates a lot of extra work in the back-end for something that shouldn't particularly be an issue. If the point you're making is in regards to `>setrolelevel` not being retroactive, that's true, but the role can simply be added manually. If it's an issue of a sense of entitlement or eliteism amongst your users "ha, my level is higher, i'm better!" then that is an issue that needs to be resolved from within your server, not a Miki solution.

Just as a note, it doesn't matter when Miki was added to the server. All users will start getting experience at the same time and Miki can't give experience on a server she's not a part of. Everyone started on a level playing field. The local level simply reflects the non-spammy activity of your users.

**Comment by bucca2** [comment]
Oh, the problem was that I was using another bot to track levels and assign roles, but it wasn’t really doing it’s job of assigning roles. I wanted to use Miki instead, but then that would be unfair for users who have been on the server a lot and would have to start over. It’s really not an elitism thing—I’ve made it clear it’s just a fun thematic thing. It’s not really a big deal now with less users because I can assign manually, I wanted to have it in place in case something happened where I couldn’t do that. I understand if it creates more work, and I wasn’t actually aware it was a global thing! Sorry about that.

**Comment by bucca2** [comment]
One last thing though—once you’ve set Miki to assign a role, is there any way to remove or change that?

**Comment by adv0catus** [comment]
I'd suggest giving people the role they "should" have with Miki manually based on their level with the old bot. Then use `>setrolelevel <role name> <level #>` to allow new users that hit those milestones to automatically get the roles as they hit the required levels.

If you change your mind and don't want a role to be actively assigned any more, change the level to 0 to disable it.

**Comment by bucca2** [comment]
That’s probably the best course of action, thanks!
