### ISSUE TITLE
Modules wont work

### ISSUE THREAD

**Issue by 2774** [veldlabs/miki-bot#372]
I was toggling the modules. First i did >showmodules and then i did >setmodule accounts disable then kept trying to re-enable it. I don't know if i'm typing it wrong because i keep typing ">setmodule accounts enable" and it keeps saying "Success! accounts have been disabled" and i've been trying to do this like ten times and it won't re-enable. Please help me. I'm getting frustrated.

**Comment by velddev** [comment]
lol i'll fix it sometime

**Comment by HeercoGrond** [comment]
So any update? A year later, this is still busted.

**Comment by velddev** [comment]
It is? I recall fixing this already.

**Comment by adv0catus** [comment]
The Accounts module won't disable now, so unable to test to confirm.

**Comment by velddev** [comment]
It works perfectly on production at the moment. 
![image](https://user-images.githubusercontent.com/13852840/54078907-73359400-42d1-11e9-9c81-33212bb589e8.png)

**Comment by adv0catus** [comment]
Was trying to edit this in, but you beat me to it:

![](https://i.imgur.com/xqdd4oc.png)

Edit: Okay, so it does work, just shows Accounts as enabled all the time regardless of whether it actually is or not.

**Comment by velddev** [comment]
It seems to be the visual result on showmodules

**Comment by HeercoGrond** [comment]
I'm witnessing my users still being able to use NSFW commands though, mind you, in a NSFW Channel. But the intent was to disable the entire NSFW Module and it simply says it activated then immediately after, the command still works. 

Edit: Alright, it works now. However the docs don't reflect the proper argumentation for the command. I was able to get it working by using `>setmodule nsfw 0` instead of `>setmodule nsfw disable`

**Comment by adv0catus** [comment]
This system of modules is depreciated with the introduction of the new permission system, I believe.
