### ISSUE TITLE
>e621 doesn't work with parameters

### ISSUE THREAD

**Issue by davpfre** [veldlabs/miki-bot#373]
Searching for specific tags with the e621 command, doesn't return an image.

**Comment by Pao-Lumu** [comment]
Also applies to `>yandere`, `>safe use:e621`, and `>safe use:konachan`.
These sites' APIs use a different JSON style than r34, gelbooru, and safebooru, which leads me to believe it's not a coincidence.

It's not having issues parsing from the API, since it's able to do that without parameters.

The only real guess that I have is that it's somehow not sending tags to the api properly, but that doesn't explain why no pictures are displaying.

**Comment by velddev** [comment]
Closing this due to #337 being the same issue.
