### ISSUE TITLE
Responds to Bots

### ISSUE THREAD

**Issue by weeeeh** [veldlabs/miki-bot#489]
**Describe the bug**
well for bots that have a say command or if you make a pasta with miki, the command will go through if you make the bot say one. i noticed someone stole all of miki's mekos this way :( . i'm assuming this is a bug because this wasn't allowed before

**To Reproduce**
just use another bot or the pasta command to make a bot use a miki command itself

**Expected behavior**
miki to ignore the command

**Comment by adv0catus** [comment]
Confirming this. When `>pasta recursion` is said, Miki replies with the same thing, saying `>pasta recursion`. Before the updates started, that would be the end of it. Now, Miki gets stuck in a small loop, because she's executing the command that she's saying herself, within the pasta.

![](https://i.imgur.com/2qRcpzM.png)

Edit:

Doesn't seem to work as originally stated, though. Can't get it to work with `>give`. Miki just says that you don't have enough mekos to do this.

![](https://i.imgur.com/NfN29K0.png)

Edit2: Misunderstood, gotcha.

**Comment by weeeeh** [comment]
thats because she has no mekos because someone took them all. if you give her some and then do it, it'd work

**Comment by TheHeroOfTrash** [comment]
Hey there, I'm the person who did it. You're missing the crucial step of needing your discord ID instead of straight tagging. If you tag like this <@![ID Number]> it'll allow you to have Miki tag herself. Hope it helps! And thanks for the Mekos. :)

**Comment by KosmicKitsune** [comment]
Hey there, I'm the person who did it. You're missing the crucial step of needing your discord ID instead of straight tagging. If you tag like this <@![ID Number]> it'll allow you to have Miki tag the user. Hope it helps! And thanks for the Mekos. If Veld would like them returned I've lost about 100 million of the 790 million.

**Comment by velddev** [comment]
This issue has been resolved. Preferably you'd either trash the mekos or give them back to Miki @TheHeroOfTrash. 👍 I looked over this when I updated the framework.
