### ISSUE TITLE
Feature Request: >Shoe

### ISSUE THREAD

**Issue by MisfitAngel** [veldlabs/miki-bot#522]
Sometimes you don't want punch, kick, or slap someone, and it's at those times Miki should let you throw a shoe. This needs to be a thing, please.

I've only found two good gifs for it so far ([1](https://s3.photobucket.com/user/VampyreTearz/media/Misc/shoethrow1_zps74dqc5xh.gif.html) and [2](https://media1.tenor.com/images/722152b154ed82c1b85f2c51289c3f5f/tenor.gif?itemid=6165689)), but if you might consider making this a thing, I can find or create more, for sure.

**Comment by MisfitAngel** [comment]
Got another one. Can't decide which I like better:

[Lights Out](https://s3.photobucket.com/user/VampyreTearz/media/Misc/showthrow2FADE_zpsfv7vfo5x.gif.html) or [Undending Shoe Throw](https://s3.photobucket.com/user/VampyreTearz/media/Misc/showthrow2_zpsqjmeqcgm.gif.html)

**Comment by adv0catus** [comment]
Hey! Thanks for the suggestion. :)

Not sure what veld is doing with reaction/action commands right now because there's been stuff planned but it's been pushed back for higher priority stuff.

Just so you know as well, there's a dedicated suggestions page on Miki's website: https://suggestions.miki.ai/

Thanks for the suggestion and keep'em coming. :)
