### ISSUE TITLE
Cleverbot html Problem

### ISSUE THREAD

**Issue by srnyx** [veldlabs/miki-bot#72]
On my server something happened to Miki. When I did @Miki she would always respond with: html other people on my server had the same problem as well. Anyone know why?

**Comment by IA-Xerise** [comment]
Cleverbot is charging for their API calls now it would cost 300USD or more a month to keep this on miki.

**Comment by velddev** [comment]
Everyone who has the same problem please read this.

In the last two month we made over 1.100.000 calls to cleverbot. This means that if I would keep this, I'd have to pay 300$+ for 500.000 calls per month. Obviously I do not have this kind of money.

To back up this logic, here is the image of the # of calls done since Miki counted it
![image](https://a.pomf.cat/ljzbtg.png)

this is since 15 december, when the API update for miki came out. Alas, thats 1.1 million calls over the course of exactly two months. resulting in 550.000 calls per month, and to get that I'd have to either get a commercial license for cleverbot, or pay $300 for a individual with a limit of 500.000, something we will easily get over.

Check out https://www.cleverbot.com/api/ if you don't believe me.

**Comment by srnyx** [comment]
Another thing happened to cleverbot. On my server she is speaking a different language. Can I fix this or supposed to be like that?

**Comment by Phanrazak** [comment]
Well, we can't change how the cleverbot choose to reply. Because it's not ours to begin with.

**Comment by TastyCookies124** [comment]
So will server owners have the ability to host the bot and add their own cleaver bot api they pay for?

**Comment by velddev** [comment]
I'll look into this feature. That gave me an idea, TastyCookies.

**Comment by TastyCookies124** [comment]
I hope I was of assistance 😊 Let me know what happens also I'm on the miki server as DJ Tasty Reaper?!?

**Comment by velddev** [comment]
Will do :)

**Comment by IA-Xerise** [comment]
This is from cleverbot.io:
![image](https://cloud.githubusercontent.com/assets/24828421/23703748/77552e4e-03cf-11e7-9af0-5ef9be4abaf9.png)
